language: elixir
matrix:
  include:
    - elixir: 1.4.0
      otp_release: 18.3
    - elixir: 1.4.0
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 19.3
    - elixir: 1.4.5
      otp_release: 20.0
    - elixir: 1.5.0
      otp_release: 20.0
notifications:
  recipients:
    - andrew@andrewtimberlake.com
