name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  MIX_ENV: test

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir: [1.9.4, 1.10.4, 1.11.4, 1.12.3, 1.13.0]
        erlang: [20.3, 21.3, 22.3, 23.3, 24.1]
        exclude:
          - elixir: 1.9.4
            erlang: 23.3
          - elixir: 1.9.4
            erlang: 24.1
          - elixir: 1.10.4
            erlang: 20.3
          - elixir: 1.10.4
            erlang: 23.3
          - elixir: 1.10.4
            erlang: 24.1
          - elixir: 1.11.4
            erlang: 20.3
          - elixir: 1.11.4
            erlang: 24.1
          - elixir: 1.12.3
            erlang: 20.3
          - elixir: 1.12.3
            erlang: 21.3
          - elixir: 1.13.0
            erlang: 20.3
          - elixir: 1.13.0
            erlang: 21.3

    steps:
      - name: Install image packages
        run: sudo apt-get install -y imagemagick ghostscript
      - uses: actions/checkout@v2
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.erlang }}
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Install dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
